name: sequenced_animations
description: "Easily create smooth and precise sequenced animation to your widgets, creating beautiful and creative animations and transitions."
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

